---
title: ActiveJob::Exceptions::ClassMethods
layout: default
---
<div class="main">
    <div class="banner">
        
            <span>Ruby on Rails 6.0.4</span><br />
        
        <div class="type">Module</div>
        <h1>
            ActiveJob::Exceptions::ClassMethods
            
        </h1>
        <ul class="files">
            
            <li><a href="../../../files/activejob/lib/active_job/exceptions_rb.html">activejob/lib/active_job/exceptions.rb</a></li>
            
        </ul>
    </div>
    <div id="bodyContent">
        <div id="content">
  

  

  
  


  

  
    <h2 id="methods">Methods</h2>
    <ul>
      
        <li>
          <a href="#method-i-discard_on">discard_on</a>
        </li>
      
        <li>
          <a href="#method-i-retry_on">retry_on</a>
        </li>
      
    </ul>
  

  

  
    

    

    

    

    <!-- Methods -->
    
    
      <h2 id="instance-public-methods">Instance Public methods</h2>
      
        <div class="method">
          <h3 id="method-i-discard_on">
            
              discard_on(*exceptions)
            
          </h3>

          
            <div class="description">
              <p>Discard the job with no attempts to retry, if the exception is raised. This is useful when the subject of the job, like an Active Record, is no longer available, and the job is thus no longer relevant.</p>

<p>You can also pass a block that&#39;ll be invoked. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<h4 id="method-i-discard_on-label-Example">Example</h4>

<pre><code>class SearchIndexingJob &lt; ActiveJob::Base
  discard_on ActiveJob::DeserializationError
  discard_on(CustomAppException) do |job, error|
    ExceptionNotifier.caught(error)
  end

  def perform(record)
    # Will raise ActiveJob::DeserializationError if the record can&#39;t be deserialized
    # Might raise CustomAppException for something domain specific
  end
end
</code></pre>
            </div>
          

          

          

          
            
            <div class="sourcecode">
              
              <p class="source-link">
                Source:
                
              </p>
              <div id="method-i-discard_on_source">
                <pre><code class="ruby"><span class="ruby-comment"># File activejob/lib/active_job/exceptions.rb, line 87</span>
<span class="ruby-keyword">def</span> <span class="ruby-identifier ruby-title">discard_on</span>(<span class="ruby-operator">*</span><span class="ruby-identifier">exceptions</span>)
  <span class="ruby-identifier">rescue_from</span>(<span class="ruby-operator">*</span><span class="ruby-identifier">exceptions</span>) <span class="ruby-keyword">do</span> <span class="ruby-operator">|</span><span class="ruby-identifier">error</span><span class="ruby-operator">|</span>
    <span class="ruby-identifier">instrument</span> <span class="ruby-value">:discard</span>, <span class="ruby-value">error:</span> <span class="ruby-identifier">error</span> <span class="ruby-keyword">do</span>
      <span class="ruby-keyword">yield</span> <span class="ruby-keyword">self</span>, <span class="ruby-identifier">error</span> <span class="ruby-keyword">if</span> <span class="ruby-identifier">block_given?</span>
    <span class="ruby-keyword">end</span>
  <span class="ruby-keyword">end</span>
<span class="ruby-keyword">end</span></code></pre>
              </div>
            </div>
            
          </div>
        
        <div class="method">
          <h3 id="method-i-retry_on">
            
              retry_on(*exceptions, wait: 3.seconds, attempts: 5, queue: nil, priority: nil)
            
          </h3>

          
            <div class="description">
              <p>Catch the exception and reschedule job for re-execution after so many seconds, for a specific number of attempts. If the exception keeps getting raised beyond the specified number of attempts, the exception is allowed to bubble up to the underlying queuing system, which may have its own retry mechanism or place it in a holding queue for inspection.</p>

<p>You can also pass a block that&#39;ll be invoked if the retry attempts fail for custom logic rather than letting the exception bubble up. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<h4 id="method-i-retry_on-label-Options">Options</h4>
<ul><li>
<p><code>:wait</code> - Re-enqueues the job with a delay specified either in seconds (default: 3 seconds), as a computing proc that the number of executions so far as an argument, or as a symbol reference of <code>:exponentially_longer</code>, which applies the wait algorithm of <code>(executions ** 4) + 2</code> (first wait 3s, then 18s, then 83s, etc)</p>
</li><li>
<p><code>:attempts</code> - Re-enqueues the job the specified number of times (default: 5 attempts)</p>
</li><li>
<p><code>:queue</code> - Re-enqueues the job on a different queue</p>
</li><li>
<p><code>:priority</code> - Re-enqueues the job with a different priority</p>
</li></ul>

<h4 id="method-i-retry_on-label-Examples">Examples</h4>

<pre><code>class RemoteServiceJob &lt; ActiveJob::Base
  retry_on CustomAppException # defaults to 3s wait, 5 attempts
  retry_on AnotherCustomAppException, wait: -&gt;(executions) { executions * 2 }

  retry_on ActiveRecord::Deadlocked, wait: 5.seconds, attempts: 3
  retry_on Net::OpenTimeout, Timeout::Error, wait: :exponentially_longer, attempts: 10 # retries at most 10 times for Net::OpenTimeout and Timeout::Error combined
  # To retry at most 10 times for each individual exception:
  # retry_on Net::OpenTimeout, wait: :exponentially_longer, attempts: 10
  # retry_on Timeout::Error, wait: :exponentially_longer, attempts: 10

  retry_on(YetAnotherCustomAppException) do |job, error|
    ExceptionNotifier.caught(error)
  end

  def perform(*args)
    # Might raise CustomAppException, AnotherCustomAppException, or YetAnotherCustomAppException for something domain specific
    # Might raise ActiveRecord::Deadlocked when a local db deadlock is detected
    # Might raise Net::OpenTimeout or Timeout::Error when the remote service is down
  end
end
</code></pre>
            </div>
          

          

          

          
            
            <div class="sourcecode">
              
              <p class="source-link">
                Source:
                
              </p>
              <div id="method-i-retry_on_source">
                <pre><code class="ruby"><span class="ruby-comment"># File activejob/lib/active_job/exceptions.rb, line 50</span>
<span class="ruby-keyword">def</span> <span class="ruby-identifier ruby-title">retry_on</span>(<span class="ruby-operator">*</span><span class="ruby-identifier">exceptions</span>, <span class="ruby-value">wait:</span> <span class="ruby-value">3</span>.<span class="ruby-identifier">seconds</span>, <span class="ruby-value">attempts:</span> <span class="ruby-value">5</span>, <span class="ruby-value">queue:</span> <span class="ruby-keyword">nil</span>, <span class="ruby-value">priority:</span> <span class="ruby-keyword">nil</span>)
  <span class="ruby-identifier">rescue_from</span>(<span class="ruby-operator">*</span><span class="ruby-identifier">exceptions</span>) <span class="ruby-keyword">do</span> <span class="ruby-operator">|</span><span class="ruby-identifier">error</span><span class="ruby-operator">|</span>
    <span class="ruby-identifier">executions</span> = <span class="ruby-identifier">executions_for</span>(<span class="ruby-identifier">exceptions</span>)

    <span class="ruby-keyword">if</span> <span class="ruby-identifier">executions</span> <span class="ruby-operator">&lt;</span> <span class="ruby-identifier">attempts</span>
      <span class="ruby-identifier">retry_job</span> <span class="ruby-value">wait:</span> <span class="ruby-identifier">determine_delay</span>(<span class="ruby-value">seconds_or_duration_or_algorithm:</span> <span class="ruby-identifier">wait</span>, <span class="ruby-value">executions:</span> <span class="ruby-identifier">executions</span>), <span class="ruby-value">queue:</span> <span class="ruby-identifier">queue</span>, <span class="ruby-value">priority:</span> <span class="ruby-identifier">priority</span>, <span class="ruby-value">error:</span> <span class="ruby-identifier">error</span>
    <span class="ruby-keyword">else</span>
      <span class="ruby-keyword">if</span> <span class="ruby-identifier">block_given?</span>
        <span class="ruby-identifier">instrument</span> <span class="ruby-value">:retry_stopped</span>, <span class="ruby-value">error:</span> <span class="ruby-identifier">error</span> <span class="ruby-keyword">do</span>
          <span class="ruby-keyword">yield</span> <span class="ruby-keyword">self</span>, <span class="ruby-identifier">error</span>
        <span class="ruby-keyword">end</span>
      <span class="ruby-keyword">else</span>
        <span class="ruby-identifier">instrument</span> <span class="ruby-value">:retry_stopped</span>, <span class="ruby-value">error:</span> <span class="ruby-identifier">error</span>
        <span class="ruby-identifier">raise</span> <span class="ruby-identifier">error</span>
      <span class="ruby-keyword">end</span>
    <span class="ruby-keyword">end</span>
  <span class="ruby-keyword">end</span>
<span class="ruby-keyword">end</span></code></pre>
              </div>
            </div>
            
          </div>
        
      
    
  
</div>

    </div>
</div>
