---
title: ActiveJob::Exceptions::ClassMethods
layout: default
---
<div class="main">
    <div class="banner">
        
            <span>Ruby on Rails 8.1.0.rc1</span><br />
        
        <div class="type">Module</div>
        <h1>
            ActiveJob::Exceptions::ClassMethods
            
        </h1>
        <ul class="files">
            
            <li><a href="../../../files/activejob/lib/active_job/exceptions_rb.html">activejob/lib/active_job/exceptions.rb</a></li>
            
        </ul>
    </div>
    <div id="bodyContent">
        <div id="content">
  

  

  
  


  

  
    <h2 id="methods">Methods</h2>
    <ul>
      
        <li>
          <a href="#method-i-after_discard">after_discard</a>
        </li>
      
        <li>
          <a href="#method-i-discard_on">discard_on</a>
        </li>
      
        <li>
          <a href="#method-i-retry_on">retry_on</a>
        </li>
      
    </ul>
  

  

  
    

    

    

    

    <!-- Methods -->
    
    
      <h2 id="instance-public-methods">Instance Public methods</h2>
      
        <div class="method">
          <h3 id="method-i-after_discard">
            
              after_discard(&amp;blk)
            
          </h3>

          
            <div class="description">
              <p>A block to run when a job is about to be discarded for any reason.</p>

<h4 id="method-i-after_discard-label-Example">Example</h4>

<pre><code>class WorkJob &lt; ActiveJob::Base
  after_discard do |job, exception|
    ExceptionNotifier.report(exception)
  end

  ...

end
</code></pre>
            </div>
          

          

          

          
          
            <details class="method__source">
              <summary>
                <span class="label">üìù Source code</span>
              </summary>

              <pre><code class="ruby"># File activejob/lib/active_job/exceptions.rb, line 131
def after_discard(&amp;blk)
  self.after_discard_procs += [blk]
end</code></pre>
              
                <a href="https://github.com/rails/rails/blob/4720fe9c00605d6ad2d50904e98a4d5522ffbce2/activejob/lib/active_job/exceptions.rb#L131" target="_blank" class="github_url">üîé See on GitHub</a>
              
            </details>
          
        </div>
        
        <div class="method">
          <h3 id="method-i-discard_on">
            
              discard_on(*exceptions, report: false)
            
          </h3>

          
            <div class="description">
              <p>Discard the job with no attempts to retry, if the exception is raised. This is useful when the subject of the job, like an Active Record, is no longer available, and the job is thus no longer relevant.</p>

<p>Passing the <code>:report</code> option reports the error through the error reporter before discarding the job.</p>

<p>You can also pass a block that‚Äôll be invoked. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<p><a href="ClassMethods.html#method-i-retry_on"><code>retry_on</code></a> and <a href="ClassMethods.html#method-i-discard_on"><code>discard_on</code></a> handlers are searched from bottom to top, and up the class hierarchy. The handler of the first class for which <code>exception.is_a?(klass)</code> holds true is the one invoked, if any.</p>

<h4 id="method-i-discard_on-label-Example">Example</h4>

<pre><code>class SearchIndexingJob &lt; ActiveJob::Base
  discard_on ActiveJob::DeserializationError
  discard_on CustomAppException, report: true
  discard_on(AnotherCustomAppException) do |job, error|
    CustomErrorHandlingCode.handle(job, error)
  end

  def perform(record)
    # Will raise ActiveJob::DeserializationError if the record can&#39;t be deserialized
    # Might raise CustomAppException for something domain specific
  end
end
</code></pre>
            </div>
          

          

          

          
          
            <details class="method__source">
              <summary>
                <span class="label">üìù Source code</span>
              </summary>

              <pre><code class="ruby"># File activejob/lib/active_job/exceptions.rb, line 109
def discard_on(*exceptions, report: false)
  rescue_from(*exceptions) do |error|
    instrument :discard, error: error do
      ActiveSupport.error_reporter.report(error, source: &quot;application.active_job&quot;) if report
      yield self, error if block_given?
      run_after_discard_procs(error)
    end
  end
end</code></pre>
              
                <a href="https://github.com/rails/rails/blob/4720fe9c00605d6ad2d50904e98a4d5522ffbce2/activejob/lib/active_job/exceptions.rb#L109" target="_blank" class="github_url">üîé See on GitHub</a>
              
            </details>
          
        </div>
        
        <div class="method">
          <h3 id="method-i-retry_on">
            
              retry_on(*exceptions, wait: 3.seconds, attempts: 5, queue: nil, priority: nil, jitter: JITTER_DEFAULT, report: false)
            
          </h3>

          
            <div class="description">
              <p>Catch the exception and reschedule job for re-execution after so many seconds, for a specific number of attempts. If the exception keeps getting raised beyond the specified number of attempts, the exception is allowed to bubble up to the underlying queuing system, which may have its own retry mechanism or place it in a holding queue for inspection.</p>

<p>You can also pass a block that‚Äôll be invoked if the retry attempts fail for custom logic rather than letting the exception bubble up. This block is yielded with the job instance as the first and the error instance as the second parameter.</p>

<p><a href="ClassMethods.html#method-i-retry_on"><code>retry_on</code></a> and <a href="ClassMethods.html#method-i-discard_on"><code>discard_on</code></a> handlers are searched from bottom to top, and up the class hierarchy. The handler of the first class for which <code>exception.is_a?(klass)</code> holds true is the one invoked, if any.</p>

<h4 id="method-i-retry_on-label-Options">Options</h4>
<ul><li>
<p><code>:wait</code> - Re-enqueues the job with a delay specified either in seconds (default: 3 seconds), as a computing proc that takes the number of executions so far as an argument, or as a symbol reference of <code>:polynomially_longer</code>, which applies the wait algorithm of <code>((executions**4) + (Kernel.rand * (executions**4) * jitter)) + 2</code> (first wait ~3s, then ~18s, then ~83s, etc)</p>
</li><li>
<p><code>:attempts</code> - Enqueues the job the specified number of times (default: 5 attempts) or a symbol reference of <code>:unlimited</code> to retry the job until it succeeds. The number of attempts includes the original job execution.</p>
</li><li>
<p><code>:queue</code> - Re-enqueues the job on a different queue</p>
</li><li>
<p><code>:priority</code> - Re-enqueues the job with a different priority</p>
</li><li>
<p><code>:jitter</code> - A random delay of wait time used when calculating backoff. The default is 15% (0.15) which represents the upper bound of possible wait time (expressed as a percentage)</p>
</li><li>
<p><code>:report</code> - Errors will be reported to the <a href="../../Rails.html#method-c-error"><code>Rails.error</code></a> reporter before being retried</p>
</li></ul>

<h4 id="method-i-retry_on-label-Examples">Examples</h4>

<pre><code>class RemoteServiceJob &lt; ActiveJob::Base
  retry_on CustomAppException # defaults to ~3s wait, 5 attempts
  retry_on AnotherCustomAppException, wait: -&gt;(executions) { executions * 2 }
  retry_on CustomInfrastructureException, wait: 5.minutes, attempts: :unlimited

  retry_on ActiveRecord::Deadlocked, wait: 5.seconds, attempts: 3
  retry_on Net::OpenTimeout, Timeout::Error, wait: :polynomially_longer, attempts: 10 # retries at most 10 times for Net::OpenTimeout and Timeout::Error combined
  # To retry at most 10 times for each individual exception:
  # retry_on Net::OpenTimeout, wait: :polynomially_longer, attempts: 10
  # retry_on Net::ReadTimeout, wait: 5.seconds, jitter: 0.30, attempts: 10
  # retry_on Timeout::Error, wait: :polynomially_longer, attempts: 10

  retry_on YetAnotherCustomAppException, report: true
  retry_on EvenWorseCustomAppException do |job, error|
    CustomErrorHandlingCode.handle(job, error)
  end

  def perform(*args)
    # Might raise CustomAppException, AnotherCustomAppException, or YetAnotherCustomAppException for something domain specific
    # Might raise ActiveRecord::Deadlocked when a local db deadlock is detected
    # Might raise Net::OpenTimeout or Timeout::Error when the remote service is down
  end
end
</code></pre>
            </div>
          

          

          

          
          
            <details class="method__source">
              <summary>
                <span class="label">üìù Source code</span>
              </summary>

              <pre><code class="ruby"># File activejob/lib/active_job/exceptions.rb, line 64
def retry_on(*exceptions, wait: 3.seconds, attempts: 5, queue: nil, priority: nil, jitter: JITTER_DEFAULT, report: false)
  rescue_from(*exceptions) do |error|
    executions = executions_for(exceptions)
    if attempts == :unlimited || executions &lt; attempts
      ActiveSupport.error_reporter.report(error, source: &quot;application.active_job&quot;) if report
      retry_job wait: determine_delay(seconds_or_duration_or_algorithm: wait, executions: executions, jitter: jitter), queue: queue, priority: priority, error: error
    else
      if block_given?
        instrument :retry_stopped, error: error do
          yield self, error
        end
        run_after_discard_procs(error)
      else
        instrument :retry_stopped, error: error
        run_after_discard_procs(error)
        raise error
      end
    end
  end
end</code></pre>
              
                <a href="https://github.com/rails/rails/blob/4720fe9c00605d6ad2d50904e98a4d5522ffbce2/activejob/lib/active_job/exceptions.rb#L64" target="_blank" class="github_url">üîé See on GitHub</a>
              
            </details>
          
        </div>
        
      
    
  
</div>

    </div>
</div>
